<?php
/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace Spryker\Zed\Ratepay\Business\Api;

class Constants
{

    /**
     * Request model types.
     */
    const REQUEST_MODEL_HEAD = 'HEAD';
    const REQUEST_MODEL_CUSTOMER = 'CUSTOMER';
    const REQUEST_MODEL_ADDRESS = 'ADDRESS';
    const REQUEST_MODEL_PAYMENT = 'PAYMENT';
    const REQUEST_MODEL_BASKET = 'BASKET';
    const REQUEST_MODEL_BASKET_ITEM = 'BASKET_ITEM';
    const REQUEST_MODEL_BANK_ACCOUNT = 'BANK_ACCOUNT';
    const REQUEST_MODEL_PAYMENT_INIT = 'PAYMENT_INIT';
    const REQUEST_MODEL_PAYMENT_REQUEST = 'PAYMENT_REQUEST';
    const REQUEST_MODEL_PAYMENT_CONFIRM = 'PAYMENT_CONFIRM';
    const REQUEST_MODEL_PAYMENT_CHANGE = 'PAYMENT_CHANGE';
    const REQUEST_MODEL_DELIVER_CONFIRM = 'CONFIRMATION_DELIVER';
    const REQUEST_MODEL_PAYMENT_CANCEL = 'PAYMENT_CANCEL';
    const REQUEST_MODEL_PAYMENT_REFUND = 'PAYMENT_REFUND';

    const REQUEST_HEADER_CONTENT_TYPE = 'text/xml; charset=UTF8';

    const REQUEST_MODEL_ADDRESS_TYPE_BILLING = 'BILLING';
    const REQUEST_MODEL_ADDRESS_TYPE_DELIVERY = 'DELIVERY';
    const REQUEST_MODEL_ADDRESS_TYPE_REGISTRY = 'REGISTRY';

    const REQUEST_CODE_SUCCESS_MATRIX = [
        self::REQUEST_MODEL_PAYMENT_INIT => 350,
        self::REQUEST_MODEL_PAYMENT_CONFIRM => 400,
        self::REQUEST_MODEL_PAYMENT_REQUEST => 402,
        self::REQUEST_MODEL_PAYMENT_CHANGE => 403,
        self::REQUEST_MODEL_DELIVER_CONFIRM => 404,
    ];

}
